version: "3"
services:
  db:
    image: postgres:14-alpine
    container_name: study-postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=study_user
      - POSTGRES_DB=study_db